### PR TITLE
WIP: Intel MKL find-module

### PR DESCRIPTION
**Pull request by albestro**
This is a proposal to start working on FindMKL. See also FindMKL proposed in #1 for merging its functionalities.

Intel provides a [link line advisor](https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor) which can be very useful for making this script the best possible (it is a JavaScript code that I can be ported in CMake, in particular see [here](https://software.intel.com/sites/products/mkl/mkl_link_line_advisor.htm) which is just the link line advisor widget).

There is room for improvement in a lot of directions; I report here just a few examples to start discussing:
- Using CMake functions to check/detect libraries parts
- Refactoring, e.g. separating MKL_CORE from the LAPACK component
- There are a lot of hard-coded things, evaluate what can be parameterized (e.g. architecture?)
- ...

### CODE REVIEW

**Comment by albestro** [comment]
MKL package has a lot of options that map to different linking lines.

When I want to create a config-file package for my project that uses MKL, I have to call `find_dependency` in it, in order to re-generate the MKL target, but I need to be able to set all options as they are set at build time, otherwise I will get all default values and so a different link line.

As a workaround, I introduced MKL_CUSTOM variables, which can be set from the script and have priority over defaults. I don't know if it is a good thing to do so.

**I'm invoking CMake Gods here.**

@halfflat @biddisco @havogt @lukasm91

**Comment by aurianer** [comment]
We may want a basic `FindMKL.cmake` and inside have the possibility decide which component to integrate to our library whether it's BLAS, LAPACK or else :)
Cause for my microbenchmark, this cmake script was a bit too complex ^^

**Comment by albestro** [comment]
@aurianer 
It is a very good point. Can you list components/options that you would like to be able to select?

**Comment by aurianer** [comment]
For my gemm microbenchmarks, I would need a BLAS component possibly, cause I'm only using `mkl_malloc`, `mkl_free`, `dgemm` and `sgemm` which need the following `find_library` :
- mkl_intel_lp64
- mkl_gnu_thread
- mkl_core
For now, I just did a basic FindMKL.cmake with those 3 libraries

**Comment by albestro** [comment]
PR #1 has been chosen as a base for MKL find-module, so I'm closing this one.

Issue #3 has been opened as a reference for the problem of components selection.

**Pull request closed without merging**
